School register/SchoolRegister.Web/Controllers/GradeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.BLL.DataModels;
using SchoolRegister.Services.Interfaces;
using SchoolRegister.ViewModels.VM;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles = "Teacher, Admin, Student, Parent")]
    public class GradeController : BaseController
    {
        private readonly IStudentService _studentService;
        private readonly IGradeService _gradeService;
        private readonly UserManager<User> _userManager;
        private readonly ITeacherService _teacherService;
        private readonly ISubjectService _subjectService;

        public GradeController(ILogger logger, IMapper mapper, IStringLocalizer localizer, IStudentService studentService, IGradeService gradeService, UserManager<User> userManager, ITeacherService teacherService, ISubjectService subjectService) : base(logger, mapper, localizer)
        {
            _studentService = studentService;
            _gradeService = gradeService;
            _userManager = userManager;
            _teacherService = teacherService;
            _subjectService = subjectService;
        }

        [Authorize(Roles = "Teacher, Admin, Student, Parent")]
        public async Task<IActionResult> GradesReport()
        {
            var user = _userManager.GetUserAsync(User).Result;

            if (_userManager.IsInRoleAsync(user, "Teacher").Result)
            {
                var teacher = await _teacherService.GetTeacherAsync(t => t.Id == user.Id);
                var students = _studentService.GetStudents();
                // ViewBag.getterName = user.Id;
                ViewBag.StudentsSelectList = new SelectList(students.Select(s => new
                {
                    Text = $"{s.FirstName} {s.LastName}",
                    Value = s.Id
                }), "Value", "Text");
                return View();
            }
            else if (_userManager.IsInRoleAsync(user, "Parent").Result)
            {
                var students = _studentService.GetStudents(x => x.ParentId == user.Id);
                // ViewBag.getterName = user.Id;
                ViewBag.StudentsSelectList = new SelectList(students.Select(s => new
                {
                    Text = $"{s.FirstName} {s.LastName}",
                    Value = s.Id
                }), "Value", "Text");
                return View();
            }
            else if (_userManager.IsInRoleAsync(user, "Student").Result)
            {

                return RedirectToAction("GetGradesReport");
            }

            return View();
        }

        [Authorize(Roles = "Teacher, Admin, Student, Parent")]
        public async Task<IActionResult> GetGradesReport(string sId)
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (User.IsInRole("Student"))
            {
                var getGradesReportVm = new GetGradesReportVm
                {
                    GetterUserId = user.Id,
                    StudentId = user.Id,
                };
                var gradesReport = await _gradeService.GetGradesReportForStudentAsync(getGradesReportVm);
                return View(gradesReport);
            }
            else
            {
                var getGradesReportVm = new GetGradesReportVm
                {
                    GetterUserId = user.Id,
                    StudentId = Convert.ToInt32(sId),
                };
                var gradesReport = await _gradeService.GetGradesReportForStudentAsync(getGradesReportVm);
                return View(gradesReport);
            }
        }

        [HttpGet]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> AddGradeToStudent(int studentId)
        {
            var student = await _studentService.GetStudentAsync(s => s.Id == studentId);
            ViewBag.Student = $"{student.FirstName} {student.LastName}";
            var subjects = _subjectService.GetSubjects(s => s.SubjectGroups.Any(sg => sg.GroupId == student.GroupId));
            ViewBag.SubjectsSelectList = new SelectList(subjects.Select(s => new
            {
                Text = $"{s.Name}",
                Value = s.Id
            }), "Value", "Text");
            ViewBag.GradeSelectList = new SelectList(Enum.GetValues(typeof(GradeScale)), "Choose grade");
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Teacher")]
        public async Task<IActionResult> AddGradeToStudent(AddGradeToStudentVm addGradeToStudentVm)
        {
            var user = _userManager.GetUserAsync(User).Result;
            addGradeToStudentVm.TeacherId = user.Id;
            await _gradeService.AddGradeToStudentAsync(addGradeToStudentVm);
            return RedirectToAction("Index", "Student");
        }

    }
}

School register/SchoolRegister.Web/Controllers/StudentController.cs
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Localization;
using Microsoft.Extensions.Logging;
using SchoolRegister.BLL.DataModels;
using SchoolRegister.DAL.EF;
using SchoolRegister.Services.Interfaces;

namespace SchoolRegister.Web.Controllers
{
    [Authorize(Roles = "Teacher, Admin, Student, Parent")]
    public class StudentController : BaseController
    {
        private readonly IStudentService _studentService;
        private readonly IGroupService _groupService;
        private readonly UserManager<User> _userManager;

        private readonly ApplicationDbContext _context;
        private readonly ITeacherService _teacherService;

        public StudentController(ILogger logger, IMapper mapper, IStringLocalizer localizer, IStudentService studentService, IGroupService groupService, UserManager<User> userManager, ApplicationDbContext context, ITeacherService teacherService) : base(logger, mapper, localizer)
        {
            _studentService = studentService;
            _groupService = groupService;
            _userManager = userManager;
            _context = context;
            _teacherService = teacherService;
        }


        public  IActionResult Index()
        {
            var user = _userManager.GetUserAsync(User).Result;
            if (_userManager.IsInRoleAsync(user, "Admin").Result)
                return View(_studentService.GetStudents());
            else if (_userManager.IsInRoleAsync(user, "Student").Result)
                return RedirectToAction("Details", "Student", new { studentId = user.Id });
            else if (_userManager.IsInRoleAsync(user, "Parent").Result)
                return View(_studentService.GetStudents(s => s.ParentId == user.Id));
            else if (_userManager.IsInRoleAsync(user, "Teacher").Result)
                return View(_studentService.GetStudents());
            else
                return View("Error");
        }

        [HttpGet]
        [Authorize(Roles = "Admin")]
        public IActionResult GetIdToDelete(int studentId)
        {
            ViewBag.Id = studentId;
            return PartialView();
        }

        [HttpPost, ActionName("GetIdToDelete")]
        [Authorize(Roles = "Admin")]
        public async Task<ActionResult> Delete(int studentId)
        {
            await _studentService.RemoveStudentAsync(studentId);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<ActionResult> Details(int studentId)
        {
            var student = await _studentService.GetStudentAsync(s => s.Id == studentId);
            // ViewBag.Parent = await _context.Users.OfType<Parent>().FirstOrDefaultAsync(p => p.Id == student.ParentId);
            return View(student);
        }
    }
}

School register/SchoolRegister.Web/Views/Student/Details.cshtml
@model SchoolRegister.ViewModels.VM.StudentVm
@using Microsoft.AspNetCore.Mvc.Localization
@using SchoolRegister.Services.Services
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = $"{Model.FirstName} {Model.LastName} {Localizer["Title"].Value}";
}

<h2>@ViewData["Title"]</h2>
<hr />
<div class="row">
    <table class="table table-hover">
        <thead>
            <tr>
                <th class="d-none">
                    @Html.DisplayNameFor(model => model.Id)
                </th>
                @if (!User.IsInRole("Parent")) {
                <th class="col-2">
                    @Localizer["Parent"]
                </th>
                }

                <th class="col-1">
                    @Html.DisplayNameFor(model => model.Email)
                </th>
                <th class="col-1">
                    @Localizer["Group"]
                </th>
                <th class="col-2">
                    @Localizer["AverageGrade"]
                </th>

                <th class="col-3">
                    @Localizer["AverageGradePerSubject"]
                </th>
                <th class="col-2">
                    @Localizer["Grades"]
                </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="d-none">
                    @Html.DisplayFor(model => model.Id)
                </td>
                @if (!User.IsInRole("Parent")) {
                    <td>
                        @Html.DisplayFor(model => model.ParentName)
                    </td>
                }
   
                <td>
                    @Html.DisplayFor(model => model.Email)
                </td>
                <td>
                    @Html.DisplayFor(model => model.GroupName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.AverageGrade)
                </td>

                <td>
                    <ul>
                        @foreach (var item in Model.AverageGradePerSubject) {
                            <li>@item.Key.FirstLetterOfEachWord(): @item.Value</li>
                        }
                    </ul>
                </td>
                <td>
                    <ul>
                    @foreach (var subject in Model.GradesPerSubject.Keys) {
                            
                            <li>     
                                @subject.FirstLetterOfEachWord():
                                @foreach (var grade in Model.GradesPerSubject[subject]) {
                                    @($"{grade}; ")
                                }
                             </li> 
                    }
                     </ul> 
                </td>
            </tr>
        </tbody>
    </table>
</div>

<div>
    <a asp-action="Index">@Localizer["Back"]</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

School register/SchoolRegister.Web/Views/Student/GetIdToDelete.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@using (Html.BeginForm("GetIdToDelete", "Student", FormMethod.Post))
{
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="myModalLabel">
                    @Localizer["ConfirmationMSG"] 
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">@Localizer["CancelButton"]</button>
                <button type="submit" asp-route-studentId="@ViewBag.Id" class="btn btn-danger">@Localizer["ConfirmationButton"]</button>
            </div>
        </div>
}

School register/SchoolRegister.Web/Views/Student/Index.cshtml
@model IEnumerable<SchoolRegister.ViewModels.VM.StudentVm>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Title"];
}

<h2>@ViewData["Title"]</h2>

<table id="tabela" class="table table-striped table-hover">
    <thead>
        <tr>
            <th class="d-none">
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th class="col-2">
                @Localizer["FirstName"]
            </th>
            <th class="col-2">
                @Localizer["LastName"]
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td class="d-none">
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td class="align-middle text-right">
                <div class="dropdown show">
                    <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuLink"
                    data-toggle="dropdown"
                    aria-haspopup="true"
                    aria-expanded="false">
                        @Localizer["Manage"]
                    </a>
                    <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        @if (User.IsInRole("Admin")) {
                           /* <a class="dropdown-item" asp-action="EditStudent" asp-route-studentId="@item.Id">
                                Edit
                            </a> 
                            <div class="dropdown-divider"></div> */

                            <a class="dropdown-item modalLink" href="#" >
                                @Localizer["Delete"]
                            </a>  
                             <div class="dropdown-divider"></div>
                            
                   }
                        @if (User.IsInRole("Admin") || User.IsInRole("Teacher") || User.IsInRole("Parent")) {
                               
                                    <a class="dropdown-item" asp-action="Details" asp-route-studentId="@item.Id">
                                        @Localizer["Details"]
                                    </a>
                                @if (!User.IsInRole("Parent")) {
                                    @if(User.IsInRole("Teacher")) {
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" 
                                    asp-controller="Grade"
                                    asp-action="AddGradeToStudent" asp-route-studentId="@item.Id">
                                        @Localizer["AddGrade"]
                                    </a>                                          
                                    }
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" 
                                    asp-controller="Group"
                                    asp-action="AttachStudentToGroup" asp-route-studentId="@item.Id">
                                        @Localizer["Attach"]
                                    </a>  
                                    @if (item.GroupId != null) {
                               <div class="dropdown-divider"></div>
                                    <a class="dropdown-item"
                                    asp-controller="Group"
                                     asp-action="DetachStudentFromGroup" asp-route-studentId="@item.Id">
                                        @Localizer["Detach"]
                                    </a> 
                                }
                                
                                    }                                                              
                        }
                    </div>
                </div>
            </td>
        </tr>
}
    </tbody>
</table>

    <div class="modal fade" id="Modalpopup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">

        </div>
    </div>

    @section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $(".modalLink").click(function () {
                var $currentId = $(this).closest("tr").children('td:first').text();
                console.log($currentId)
                $.ajax({
                    url: "@Url.Action("GetIdToDelete", "Student")",
                    data: {
                        studentId: $currentId
                    },
                    success: function (data) {
                        $(".modal-dialog").html(data);
                        $("#Modalpopup").modal('show');
                    }
                });
            })
        })
    </script>
    }